apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: postgres
    spec:
      spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "role"
                operator: In
                values: ["app"]
      containers:
      - name: app
        image: soura49/restapi:postgres-restapi-0
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 500m
            memory: 20Mi
          requests:
            cpu: 500m
            memory: 20Mi
      nodeSelector:
        role: app
