apiVersion: v1
kind: Service
metadata:
  name: postgresstate
  labels:
    app: postgresstate
spec:
  selector:
    app: postgresstate
  ports:
  - name: http
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: NodePort
