apiVersion: v1
kind: Service
metadata:
  name: restapi
  labels:
    app: restapi
spec:
  selector:
    app: restapi
  ports:
  - name: http
    port: 8088
    targetPort: http
    protocol: TCP
  type: NodePort
